services:
  - type: web
    name: my-route-api
    env: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: my-route-webapp
    env: static
    rootDir: webapp
    staticPublishPath: .
